on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PR_NUMBER: anil

name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
    
    - name: check pull request
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      env:
        GH_TOKEN: ${{ secrets.GIT_TOCKEN }}

    - name: print
      run: echo $PR_NUMBER
